FROM node:22-alpine AS build
WORKDIR /app

# Install git
RUN apk add --no-cache git

# Clone the frontend repository
RUN git clone https://github.com/TheNerdsHub/NerdHub-Frontend.git .
WORKDIR /app/NerdHub-Frontend

# Install dependencies and build the project
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]